// Package template provides functionality to generate a .env.template file
// from one or more parsed environment maps, replacing values with empty strings
// or placeholder hints.
package template

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// Options controls how the template is rendered.
type Options struct {
	// Placeholder is written as the value for each key.
	// Defaults to empty string if not set.
	Placeholder string
	// IncludeComments adds a header comment to the output.
	IncludeComments bool
}

// DefaultOptions returns an Options with sensible defaults.
func DefaultOptions() Options {
	return Options{
		Placeholder:     "",
		IncludeComments: true,
	}
}

// Generate writes a .env template to w using the union of keys from all
// provided environment maps. Values are replaced with opts.Placeholder.
func Generate(w io.Writer, envs []map[string]string, opts Options) error {
	keys := unionKeys(envs)
	sort.Strings(keys)

	if opts.IncludeComments {
		_, err := fmt.Fprintln(w, "# Auto-generated by envdiff. Fill in values before use.")
		if err != nil {
			return err
		}
	}

	for _, key := range keys {
		line := formatLine(key, opts.Placeholder)
		if _, err := fmt.Fprintln(w, line); err != nil {
			return err
		}
	}
	return nil
}

func formatLine(key, placeholder string) string {
	if placeholder == "" {
		return key + "="
	}
	// Quote placeholder if it contains spaces.
	if strings.ContainsAny(placeholder, " \t") {
		return fmt.Sprintf("%s=\"%s\"", key, placeholder)
	}
	return key + "=" + placeholder
}

func unionKeys(envs []map[string]string) []string {
	seen := make(map[string]struct{})
	for _, env := range envs {
		for k := range env {
			seen[k] = struct{}{}
		}
	}
	keys := make([]string, 0, len(seen))
	for k := range seen {
		keys = append(keys, k)
	}
	return keys
}
